# ============================================================
# Docker 环境配置文件
# 此文件用于 Docker Compose 部署时使用
# ============================================================

# -----------------------------------------------------------------
# QQ 平台机器人配置
# -----------------------------------------------------------------
bot:
  appid: "102291722"
  token: "r8OshiDrfLIb2DTF29xWTKhAksdgBSV3"
  secret: "Sn8TpBXtFbxKh4RoBYwKi6UsGe3SrGf4"
  sandbox: false

# -----------------------------------------------------------------
# HeyBox (小黑盒) 平台配置
# -----------------------------------------------------------------
heybox:
  enabled: true
  token: "ODUwMTg4MjU7MTc1MzA3OTA1NDQ0MTkwOTQ2NTsxNDQ5MDAzMDQyODA4ODc3MzY5"

# -----------------------------------------------------------------
# Kook (开黑啦) 平台配置
# -----------------------------------------------------------------
kook:
  enabled: true
  token: "1/Mzg1NTU=/Dyo3wh4AFs+QSksh0Qk+Uw=="

# -----------------------------------------------------------------
# 性能配置
# -----------------------------------------------------------------
max_concurrent: 5
max_workers: 10

# -----------------------------------------------------------------
# 调试与开发配置
# -----------------------------------------------------------------
debug:
  enabled: true
  test_reply: false
  message_id: false
  local_mode: false  # Docker 环境建议设为 false

# -----------------------------------------------------------------
# 网络代理配置
# -----------------------------------------------------------------
proxy:
  enabled: false
  host: "127.0.0.1"
  port: 7890
  type: "http"

# -----------------------------------------------------------------
# The Finals API 数据源配置
# -----------------------------------------------------------------
api:
  use_proxy: false
  standard:
    base_url: "https://thefinals.xiaoyueyou.sdjz.wiki/https:/api.the-finals-leaderboard.com/"
  proxy:
    base_url: ""
  backup:
    base_url: "https://thefinals.xiaoyueyou.sdjz.wiki/https:/api.the-finals-leaderboard.com/"

# -----------------------------------------------------------------
# API 服务器配置
# -----------------------------------------------------------------
server:
  api:
    enabled: true
    host: "0.0.0.0"
    port: 8080
    external_url: "https://api-qqbot.sdjz.wiki:8444"
  message: "欢迎使用 THE FINALS BOT API"
  tv_ver: "1.0.0"

# -----------------------------------------------------------------
# 赛季配置
# -----------------------------------------------------------------
season:
  current: "s8"
  update_interval: 120
  end_time: "2025-12-11 00:00:00"

# -----------------------------------------------------------------
# 翻译功能配置
# -----------------------------------------------------------------
translation:
  enabled: true
  file: "data/translations.json"

# -----------------------------------------------------------------
# 图片发送与存储配置
# -----------------------------------------------------------------
image:
  send_method: "url"
  storage:
    path: "static/temp_images"
    lifetime: 24
    cleanup_interval: 1

# -----------------------------------------------------------------
# Redis 配置（Docker 环境）
# -----------------------------------------------------------------
redis:
  host: "redis"  # Docker Compose 中的服务名
  port: 6379
  db: 0
  password: ""
  timeout: 5

# -----------------------------------------------------------------
# 公告功能配置
# -----------------------------------------------------------------
announcements:
  enabled: true
  items:
    - id: down_20250907
      message: |-
        【机器人服务中断说明】
        抱歉再再再次打扰，工具箱服务中断问题现已完成修复
        本次原因依然源于服务商服务器数据盘损坏导致全部数据丢失
        不过还好我本地有一份备份文件，嘻嘻
      start_time: '2025-09-07 19:00:00'
      end_time: '2025-09-07 23:59:59'

