"""Store common template strings or elements."""

SEPARATOR = "-------------"

# 加长变体
SEPARATOR_PLUS_1 = SEPARATOR + "-"
SEPARATOR_PLUS_2 = SEPARATOR + "--"
SEPARATOR_PLUS_3 = SEPARATOR + "---"
SEPARATOR_PLUS_4 = SEPARATOR + "----"
SEPARATOR_PLUS_5 = SEPARATOR + "-----"

# 缩短变体
SEPARATOR_MINUS_1 = SEPARATOR[:-1]
SEPARATOR_MINUS_2 = SEPARATOR[:-2]
SEPARATOR_MINUS_3 = SEPARATOR[:-3]
SEPARATOR_MINUS_4 = SEPARATOR[:-4]
SEPARATOR_MINUS_5 = SEPARATOR[:-5]